refactor(snap): edgex-snap-hooks related upgrade
edgexfoundry/app-service-configurable pull request #450
Opened 2022-07-22 15:02 UTC by MonicaisHer

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/app-service-configurable/blob/main/.github/CONTRIBUTING.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [ ] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

## New Dependency Instructions (If applicable)

2022-07-26 12:55 UTC, farshidtz commented
@MonicaisHer please complete the PR template.

2022-07-26 13:50 UTC, MonicaisHer commented
> @MonicaisHer please complete the PR template (description, checklist).

Thanks, updated.

2022-07-26 15:10 UTC, farshidtz requested changes

2022-07-26 15:10 UTC, farshidtz commented on snap/local/bin/source-env-file.sh
> +    source "$SERVICE_ENV" set
Please update to:
- add the app name as syslog tag
- change SERVICE_ENV to something more clear

2022-07-26 15:10 UTC, farshidtz commented on snap/local/helper-go/Makefile
> +	[ "`gofmt -l .`" = "" ]
This can be removed. We have no unit tests and go vet is never called.

2022-07-26 15:10 UTC, farshidtz commented on snap/local/helper-go/configure.go
> +	if err != nil {
The returned error isn't read.

2022-07-26 15:10 UTC, farshidtz commented on snap/local/helper-go/configure.go
> +		return errors.New(fmt.Sprintf("profile %s has no configuration.toml", prof))
```suggestion
		return fmt.Errorf("profile %s has no configuration.toml", prof)
```

2022-07-27 15:51 UTC, farshidtz commented
@MonicaisHer I moved the startup options handling code from `source-env-file.sh` to `service-wrapper.sh` because the code has nothing to do with loading of an env file. Please check https://github.com/edgexfoundry/app-service-configurable/pull/450/commits/94b17e45cf4e6fecfae86380ac179a745ee14f92.

2022-07-27 16:20 UTC, farshidtz approved these changes
Looks good. Thanks.
@MonicaisHer, we can merge if you agree with my final refactoring.

2022-07-28 05:59 UTC, MonicaisHer commented
> Looks good. Thanks. @MonicaisHer, we can merge if you agree with my final refactoring.

Thanks for the change. Looks good to me.

2022-07-28 14:09 UTC, merged